extends: airbnb-base
plugins:
  - import
rules:
  semi: off
  comma-dangle:
    - error
    - never
  object-property-newline: off
  space-in-parens:
    - error
    - never
    - exceptions:
      - ()
  arrow-body-style: off
  brace-style:
    - error
    - stroustrup
    - allowSingleLine: true
  no-else-return: off
