extends: airbnb-base
globals:
  WebSocket: true
plugins:
  - import
rules:
  max-len: off
  semi: off
  comma-dangle:
    - error
    - never
  object-property-newline: off
  space-in-parens: off
  arrow-body-style: off
  brace-style:
    - error
    - stroustrup
    - allowSingleLine: true
  no-else-return: off
